<?php
// phpcs:disable WordPress,Squiz,PSR1,SlevomatCodingStandard,Apermo.PHP.RequireNotInclude,Generic,PSR2,PEAR,Universal
// phpcs:disable Apermo.PHP.ExplainCommentedOutCode,Apermo.PHP.ForbiddenObjectCast
// phpcs:disable Apermo.WhiteSpace,Apermo.Formatting,Apermo.Arrays,Apermo.Hooks
// phpcs:disable Apermo.Functions,Apermo.DataStructures,Apermo.WordPress
// die should be flagged (line 6).
die;
// die() should be flagged (line 8).
die();
// bare exit should be flagged (line 10).
exit;
// exit() should be allowed (line 12).
exit();
