name: Validate Conventional Commits

on:
    pull_request:
        types: [opened, synchronize, reopened]
    push:
        branches:
            - main

jobs:
    validate:
        uses: apermo/reusable-workflows/.github/workflows/reusable-conventional-commits.yml@main
        with:
            allowed-types: 'feat|fix|docs|style|refactor|test|chore|perf'
